import os
from fastapi import FastAPI, UploadFile, File, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from dotenv import load_dotenv
import json
from fastapi import Depends
from database import get_db
import models, schemas
from fastapi.security import APIKeyHeader
from fastapi import Response
from processors.report_gen import generate_pdf

# Create database tables
import models
from database import engine
models.Base.metadata.create_all(bind=engine)

# Import your existing logic (moved to the processors folder)
from processors.ocr_engine import extract_text_from_bytes
from processors.claim_auditor import audit_claim, configure_groq
import database, schemas

load_dotenv()
app = FastAPI(title="MediAudit API")
POLICY_DIR = os.path.join(os.path.dirname(__file__), "policies")
# Force the key into the auditor
api_key = os.getenv("GROQ_API_KEY")
if not api_key:
    print("❌ ERROR: GROQ_API_KEY not found in .env file!")
else:
    configure_groq(api_key)
# Allow React Frontend (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"], # React Vite port
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize Groq once
configure_groq(os.getenv("GROQ_API_KEY"))

@app.get("/")
def read_root():
    return {"status": "MediAudit Backend is Running"}

@app.post("/audit/upload", response_model=schemas.AuditResponse)
async def process_bill(file: UploadFile = File(...)):
    """
    Endpoint 1: Uploads a bill, runs OCR, and returns extracted text.
    """
    if not file.content_type.startswith("image/") and file.filename.split('.')[-1] not in ['pdf']:
        raise HTTPException(status_code=400, detail="Invalid file type")
    
    contents = await file.read()
    try:
        from groq import Groq
        client = Groq(api_key=os.getenv("GROQ_API_KEY"))
        
        extracted_text = extract_text_from_bytes(contents, file.filename, client)
        return {"filename": file.filename, "extracted_text": extracted_text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/audit/cross-check")
async def cross_check(data: schemas.CrossCheckRequest, db: Session = Depends(get_db)):
    # 1. Load the policy content from the file based on the name sent by frontend
    policy_path = os.path.join(POLICY_DIR, f"{data.policy_name}.json")
    
    if not os.path.exists(policy_path):
        raise HTTPException(status_code=404, detail=f"Policy {data.policy_name} not found")
        
    with open(policy_path, 'r') as f:
        policy_content = f.read() # Load the JSON rules as a string

    # 2. Now run the audit using the loaded content
    try:
        result = audit_claim(
            bill_text=data.bill_text,
            policy_baseline_text=policy_content
        )
        
        verdict_str = result.get('eligibility', {}).get('verdict', 'Under Review')
        
        new_audit = models.AuditRecord(
            filename=data.filename,
            insurer_name=data.insurer_name,
            verdict=verdict_str,
            analysis=result  # Stores the full JSON analysis
        )
        db.add(new_audit)
        db.commit()      # Save to PostgreSQL
        db.refresh(new_audit) # This fetches the new ID generated by the DB
        
        # --- RETURN BOTH ID AND ANALYSIS ---
        return {
            "id": new_audit.id, 
            "analysis": result
        }
    except Exception as e:
        db.rollback() # Undo DB changes if something crashed
        import traceback
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))
    
# 2. Add the History Route
@app.get("/audit/history")
async def get_history(db: Session = Depends(get_db)):
    # This fetches all records from PostgreSQL, newest first
    records = db.query(models.AuditRecord).order_by(models.AuditRecord.timestamp.desc()).all()
    
    # We need to format the data slightly for the frontend
    formatted_history = []
    for r in records:
        # Calculate an average risk score from the JSON analysis for the table view
        rows = r.analysis.get('rows', [])
        avg_risk = sum(int(row.get('risk_score', 0)) for row in rows) // len(rows) if rows else 0
        
        formatted_history.append({
            "id": r.id,
            "filename": r.filename,
            "insurer_name": r.insurer_name,
            "verdict": r.verdict,
            "risk_score": avg_risk,
            "timestamp": r.timestamp.isoformat()
        })
    return formatted_history
@app.get("/api/policies")
async def get_policies():
    """Returns a list of available insurance policy JSONs for the frontend dropdown."""
    try:
        # Check if the directory exists to avoid crashes
        if not os.path.exists(POLICY_DIR):
            return {"policies": []}
            
        # List all .json files and strip the extension for the UI
        files = [f for f in os.listdir(POLICY_DIR) if f.endswith('.json')]
        policy_names = [f.replace('.json', '') for f in files]
        
        return {"policies": policy_names}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    
@app.get("/audit/download/{audit_id}")
async def download_report(audit_id: int, db: Session = Depends(get_db)):
    # 1. Fetch data from DB
    audit = db.query(models.AuditRecord).filter(models.AuditRecord.id == audit_id).first()
    if not audit:
        raise HTTPException(status_code=404, detail="Audit not found")

    # 2. Format data for the PDF generator
    report_data = {
        "insurer_name": audit.insurer_name,
        "filename": audit.filename,
        "verdict": audit.verdict,
        "rows": audit.analysis.get('rows', []),
        "eligibility_summary": audit.analysis.get('eligibility', {}).get('summary', '')
    }

    # 3. Generate PDF bytes
    pdf_bytes = generate_pdf(report_data)

    # 4. Return as a file download
    headers = {'Content-Disposition': f'attachment; filename="MediAudit_Report_{audit_id}.pdf"'}
    return Response(content=pdf_bytes, headers=headers, media_type="application/pdf")